# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#Função para analisar as vendas
def analisar_vendas():
    global limite_seguranca
    media = sum(vendas)/len(vendas)
    print(f"O valor medio das vendas é: {media:.2f}")
    print("-" * 40)
    if media > limite_seguranca:
        print("SISTEMA EM QUARENTENA")
        print("-" * 40)
    #laço para indicação de revisão manual (discrepancia detectada)
    for venda in vendas:
        if venda > 5 * media:
            print("DISCREPÂNCIA DETECTADA (Revisão manual indicada).")
            print("-" * 40)
            break
    #Lanço para edição dos valores
    for venda in vendas:
        if venda > limite_seguranca:
            novo_valor = input(f"a venda {venda:.2f} ultrapassou o limite de segurança. Deseja alterar o limte ? sim / nao: ").lower()
            if novo_valor == "sim":
                n_limite = float(input("Digite o novo limite de segurança: "))
                limite_seguranca = n_limite
                print("Novo limite de segurança definido")
                print("-" * 40)
                break
            elif novo_valor == "nao":
                print("Usuario definiu valor antigo ainda como Limite de segurança")
                print("-" * 40)
                break
            else:
                print("Erro, comando incorreto")
                print("-" * 40)

# Initialize limite_seguranca before it's used
limite_seguranca = float(input("Digite o limite de segurança inicial: "))
print("-" * 40)

#Lista com o valores das 3 vendas:
vendas = []
for i in range(3):
    valor = float(input(f"Digite o valor da venda {i + 1}: "))
    print("-" * 40)
    vendas.append(valor)

analisar_vendas()

for venda in vendas:
    print(f'Valor: {venda:.2f}\nTipo da variável: {type(venda)}')